apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: bgpdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ["node02.bgp-data.net"]
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        env:
        - name: CLOUDFLARE_TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-secret
              key: tunnel-token
        command: ["cloudflared", "tunnel", "run", "--token", "$(CLOUDFLARE_TUNNEL_TOKEN)"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          exec:
            command:
            - cloudflared
            - --version
          initialDelaySeconds: 10
          periodSeconds: 30