apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: bgpdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: bgpdata/postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "bgpdata"
        - name: POSTGRES_USER
          value: "bgpdata"
        - name: POSTGRES_DB
          value: "bgpdata"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: timescale-data
          mountPath: /var/lib/postgresql/ts
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - bgpdata
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - bgpdata
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
      - name: timescale-data
        persistentVolumeClaim:
          claimName: timescale-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: bgpdata
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
