name: Main

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/base:latest

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_TOKEN }}

      - name: Replace secrets placeholders
        run: |
          DOCKER_CONFIG_JSON=$(echo -n '{"auths":{"docker.io":{"username":"'${{ secrets.DOCKERHUB_USERNAME }}'","password":"'${{ secrets.DOCKERHUB_TOKEN }}'","auth":"'$(echo -n '${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}' | base64 -w 0)'"}}}' | base64 -w 0)
          sed -i -e "s/{{CLOUDFLARE_TUNNEL_TOKEN}}/${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}/g" \
                  -e "s/{{FLASK_SECRET_KEY}}/${{ secrets.FLASK_SECRET_KEY }}/g" \
                  -e "s/{{POSTMARK_API_KEY}}/${{ secrets.POSTMARK_API_KEY }}/g" \
                  -e "s/{{GRAFANA_ADMIN_PASSWORD}}/${{ secrets.GRAFANA_ADMIN_PASSWORD }}/g" \
                  -e "s/{{DOCKER_CONFIG_JSON}}/$DOCKER_CONFIG_JSON/g" \
                  k8s/secrets.yaml

      - name: Deploy to K8s
        run: |
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/namespace.yaml
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/secrets.yaml
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/pvc.yaml
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/postgres.yaml
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/zookeeper.yaml
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/kafka.yaml
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/aggregator.yaml
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/whois.yaml
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/web.yaml
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/cloudflared.yaml
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/collectors.yaml
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/relays.yaml
          ssh root@$ctrl01 "kubectl apply -f -" < k8s/grafana.yaml

      - name: Verify deployment
        run: |
          ssh root@$ctrl01 "kubectl get pods -n bgpdata -o wide"
          ssh root@$ctrl01 "kubectl get svc -n bgpdata"
          ssh root@$ctrl01 "kubectl get pvc -n bgpdata"