name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/base:latest

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}

      - name: Deploy to K3s
        # This is a workaround to deploy the YAML files to the K3s cluster.
        # We open a ssh tunnel to the K3s cluster and deploy the YAML files to it.
        run: |
          YAML_CONTENT="$(for file in k3s/*.yaml; do [ -f "$file" ] && { printf '%s\n' "---"; cat "$file"; }; done)"          
          echo "$YAML_CONTENT" | ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "kubectl apply -f -"